name             'hubrick'
maintainer       'Eyal Zekaria'
maintainer_email 'eyal.ez@gmail.com'
license          'All rights reserved'
description      'Installs/Configures hubrick'
long_description 'Installs/Configures hubrick'
version          '0.1.0'
